/**
 * Regenerates src/lib/overture-categories.ts from the taxonomy Overture
 * publishes alongside each release, so the Swarm import can tell a real
 * Overture category code from a guess made out of a Foursquare name.
 *
 *   npm run overture:categories                  # the release in OVERTURE_RELEASE
 *   npm run overture:categories -- 2026-09-23.0
 */

import "../src/load-environment.js";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const release = process.argv[2] ?? process.env.OVERTURE_RELEASE;
if (!release) {
  console.error("Pass a release such as 2026-09-23.0, or set OVERTURE_RELEASE");
  process.exit(1);
}

const url = `https://raw.githubusercontent.com/OvertureMaps/docs/main/static/taxonomy/${release}/taxonomy_to_legacy_categories.csv`;
const response = await fetch(url);
if (!response.ok) {
  throw new Error(`${url} answered ${response.status}`);
}

const lines = (await response.text()).split("\n").filter((line) => line.trim().length > 0);
// The first two columns are category codes and never contain a comma; the
// display names further along may, which is why only those columns are read.
const header = lines[0]!.split(",");
const primaryColumn = header.indexOf("taxonomy_primary");
if (primaryColumn === -1) {
  throw new Error(`Expected a taxonomy_primary column; got ${header.join(", ")}`);
}

const codes = new Set<string>();
for (const line of lines.slice(1)) {
  const code = line.split(",")[primaryColumn]?.trim();
  if (code) {
    codes.add(code);
  }
}
const sorted = [...codes].sort();

const output = `// Generated by scripts/generate-overture-categories.ts from Overture release ${release}.
// Do not edit by hand: run \`npm run overture:categories\` instead.

/**
 * Every category code in Overture's places taxonomy, as the \`places\` table
 * spells them in \`primary_type\` and \`types\`. Used to check that a code
 * derived from another source's category name is one Overture has.
 */
export const OVERTURE_CATEGORIES: ReadonlySet<string> = new Set([
${sorted.map((code) => `  "${code}",`).join("\n")}
]);
`;

writeFileSync(fileURLToPath(new URL("../src/lib/overture-categories.ts", import.meta.url)), output);
console.log(`${sorted.length} categories written from release ${release}`);
